/*
Copyright © 2020 Alessandro Segala (@ItalyPaleAle)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
*/

package fs

import (
	"fmt"

	"github.com/ItalyPaleAle/prvt/utils"
)

// RequestRange is used to request a range of data only
// This function uses both bytes and packages, as generated by minio/sio; each package is 64KB + 32 bytes
type RequestRange struct {
	// Start of the range that is requested from the plaintext, in bytes
	Start int64
	// Amount of data requested in plaintext, from the Start byte
	Length int64
	// Size of the header added by prvt at the beginning of the file (encoded crypto.Header, including size byte)
	HeaderOffset int64
	// Size of the encoded metadata object added at the beginning of the plaintext (encoded crypto.Metadata, including 2 size bytes)
	MetadataOffset int64
}

// NewRequestRange returns a new RequestRange object from a HttpRange one
func NewRequestRange(rng utils.HttpRange, ho, mo int64) *RequestRange {
	return &RequestRange{
		Start:          rng.Start,
		Length:         rng.Length,
		HeaderOffset:   ho,
		MetadataOffset: mo,
	}
}

// StartPackage returns the start package number
func (c *RequestRange) StartPackage() int64 {
	// This is rounded down always
	return (c.Start + c.MetadataOffset) / (64*1024 + 32)
}

// EndPackage returns the end package number
func (c *RequestRange) EndPackage() int64 {
	// Adding +1 to round up
	return (c.Start+c.Length+c.MetadataOffset)/(64*1024+32) + 1
}

// LengthPackages returns the number of packages that need to be requested
func (c *RequestRange) LengthPackages() int64 {
	return c.EndPackage() - c.StartPackage()
}

// StartBytes returns the start value in bytes
// That's the start range for the request to the fs
func (c *RequestRange) StartBytes() int64 {
	return (c.StartPackage() * (64*1024 + 32)) + c.HeaderOffset
}

// EndBytes returns the end value in bytes
// Thats the end range for the request to the fs
func (c *RequestRange) EndBytes() int64 {
	return (c.EndPackage() * (64*1024 + 32)) + c.HeaderOffset
}

// LengthBytes returns the number of bytes that need to be requested
func (c *RequestRange) LengthBytes() int64 {
	return c.LengthPackages() * (64*1024 + 32)
}

// HeaderValue returns the value for the Range HTTP reader, in bytes
func (c *RequestRange) HeaderValue() string {
	return fmt.Sprintf("bytes=%d-%d", c.StartBytes(), c.EndBytes())
}
