version: '3'

services:
  workspace:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # Go version
        VARIANT: '1.15'
        # Enable installing Node.js and specify the version
        INSTALL_NODE: 'true'
        NODE_VERSION: '14'
    networks:
      - prvt-dev
    restart: unless-stopped
    #ports:
    #  - 127.0.0.1:3129:3129
    #  - 127.0.0.1:3000:3000
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/home/vscode/workspace:cached
      - shell-history:/shell-history
      - prvt-local:/home/vscode/prvt-data
    # Overrides default command so things don't shut down after the process ends
    command: sleep infinity 
    # Use a non-root user for all processes
    user: vscode
    # Enable certain capabilities that are necessary for debugging Go apps
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp=unconfined
    # Environmental variables
    environment:
      - 'GPGKEY_ID=0x4C6D7DB1D92F58EE'
      - 'GPGKEY_ID_FULL=26426A3E380F1D1B67031D3C4C6D7DB1D92F58EE'
      - 'GPGKEY_USER=prvt CI <ci@prvt>'
      - 'S3_ENDPOINT=minio:9000'
      - 'S3_TLS=false'
      - 'AZURE_STORAGE_ACCOUNT=devstoreaccount1'
      - 'AZURE_STORAGE_ACCESS_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw=='
      - 'AZURE_STORAGE_CUSTOM_ENDPOINT=azurite:10000'
      - 'AZURE_STORAGE_TLS=false'
      - 'AZURE_STORAGE_CONNECTION_STRING=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1'
      - 'AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE'
      - 'AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
      - 'PRVT_STORE=local:/home/vscode/prvt-data'
  minio:
    image: minio/minio
    command: 'server /data'
    volumes:
      - minio-data:/data
    networks:
      prvt-dev:
        aliases: 
          - minio
    restart: unless-stopped
    ports:
      - 127.0.0.1:9000:9000
    environment:
      - 'MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE'
      - 'MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    command: 'azurite-blob -l /data --blobHost 0.0.0.0 --blobPort 10000'
    restart: unless-stopped
    networks:
      prvt-dev:
        aliases: 
          - azurite
    volumes:
      - azurite-data:/data
    ports:
      - 127.0.0.1:10000:10000

volumes:
  minio-data:
  azurite-data:
  shell-history:
  prvt-local:

networks:
  prvt-dev:
